Fixed rust compilation error `#[deny(invalid_macro_export_arguments)]` in src/utils.rs:5:1
Changed #[macro_export()] to #[macro_export] since rust wont compile with empty arguments
See issue <https://github.com/rust-lang/rust/issues/57571>